addSbtPlugin("org.scoverage"           % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("com.typesafe.sbt"        % "sbt-native-packager" % "1.6.1")
addSbtPlugin("org.wartremover"         % "sbt-wartremover"     % "2.4.2")
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc"       % "0.8.2")
addSbtPlugin("com.lightbend.sbt"       % "sbt-javaagent"       % "0.1.5")